### ISSUE TITLE
Tray Interface for Betty?

### ISSUE THREAD

**Issue by johnku1** [pickhardt/betty#154]
While looking for news articles about Betty, I found this:
http://spiceofdesign.deviantart.com/art/Betty-virtual-assistant-454243160
Would something like this be feasible to implement?

**Comment by TRoskop** [comment]
This Design Concept looks wonderfull!
The Problem is only that Betty return very complex result string:

-----
$ betty what is my name
Betty: Okay, I have multiple ways to respond.
Betty: Enter the number of the command you want me to run, or N (no) if you don't want me to run any.
[1] whoami
    Gets your system username.
[2] finger $(whoami) | sed 's/.*: *//;q'
    Gets your full name.
1
Betty: Running whoami
******

So this would fill the UI to fast.
If Betty can have more simple interfaces, then It would be very easy to create a GUI (in QT for example :smile:  ).

**Comment by TRoskop** [comment]
Here you have a more detailed Info about the UI:
https://github.com/pickhardt/betty/issues/164

**Comment by pickhardt** [comment]
Cool UI. If any of you want to be a maintainer of this project I could add you to the list. I don't actively maintain it currently. Let me know.

**Comment by x-a-n-a-x** [comment]
Huh. ![smiley-surprised](https://cloud.githubusercontent.com/assets/1732773/9868036/473b0210-5b74-11e5-984d-8655c8a3f7eb.gif)
 Why do you close issues if the idea/feature hasn't been implemented? Afaik, Github issues must be kept open until the task/work is not finished..

**Comment by pickhardt** [comment]
I mean, I can close whatever issue I want, there's no rule about keeping them open. In this case though I closed it because TRoskop made one:
https://github.com/TRoskop/Betty-UI

See also:
https://github.com/pickhardt/betty/issues/164
